trello123/Disboard-demo-

app/models/board.rb
app/models/board_user.rb
app/models/card.rb
app/models/container.rb
app/models/user.rb
db/migrate/20230420094856_create_boards.rb
db/migrate/20230420094857_create_board_users.rb
db/migrate/20230420094858_create_containers.rb
db/migrate/20230420100520_add_container_id_to_card.rb
db/schema.rb
spec/models/board_spec.rb
spec/models/board_user_spec.rb
spec/models/container_spec.rb

建立 Board, Container model 及 關聯
建立 Container 跟 Card 建立關聯

建立 Board, Container model 及 關聯

---

app/controllers/application_controller.rb
app/controllers/boards_controller.rb
app/helpers/boards_helper.rb
app/models/board.rb
app/views/boards/_board.html.erb
app/views/boards/destroy.turbo_stream.erb
app/views/boards/edit.html.erb
app/views/boards/index.html.erb
app/views/boards/show.html.erb
config/routes.rb
spec/features/board_spec.rb
spec/features/card_spec.rb
test/controllers/cards_controller_test.rb

https://user-images.githubusercontent.com/120033213/233774004-f1bfe1c6-2cea-4839-b5dd-90732e7f06b4.mp4
完成功能
-  board model CRUD
-  新增 board 後自動新增 todo doing done 的 container
-  board 名稱的 turbo frame 以及 刪除board的 turbo stream

board model CRUD

---

app/assets/stylesheets/application.tailwind.css
app/javascript/controllers/index.js
app/javascript/controllers/modal_controller.js
app/javascript/controllers/sortable_controller.js
app/models/card.rb
app/views/cards/_card.html.erb
app/views/cards/index.html.erb
app/views/devise/registrations/new.html.erb
app/views/devise/sessions/new.html.erb
app/views/homepages/index.html.erb
app/views/layouts/application.html.erb
app/views/layouts/homepage.html.erb
app/views/shared/_sidebar.html.erb

https://user-images.githubusercontent.com/87931968/233793183-daa4a68d-2b6e-43d1-b53e-4e70230e8dc5.mov

#Issue19登入彈出跟sidebar樣式

---

app/javascript/controllers/calendar_controller.js
app/javascript/utils/notify.js
package.json
yarn.lock

https://user-images.githubusercontent.com/72022753/234194193-bcf4978e-3c81-47bc-9148-cfb29e5f3774.mov

套件 sweetalert2

---

app/models/board.rb
app/models/container.rb
db/migrate/20230426045745_add_deleted_at_to_board.rb
db/migrate/20230426045848_add_deleted_at_to_container.rb
db/schema.rb

https://user-images.githubusercontent.com/130055767/234484330-1685a3c9-1ef0-4f08-9ed9-d6e09f76ee00.mp4
- board  軟刪除
- container  軟刪除

add boread container deleted_at

---

app/assets/stylesheets/application.tailwind.css
app/views/boards/show.html.erb
app/views/containers/_container.html.erb
app/views/layouts/application.html.erb
app/views/shared/_insidebar.html.erb
app/views/shared/_sidebar.html.erb

#issue#54主頁面樣式

---

app/controllers/application_controller.rb
app/controllers/cards_controller.rb
app/controllers/containers_controller.rb
app/views/cards/_card.html.erb
app/views/cards/_form.html.erb
app/views/cards/edit.html.erb
app/views/cards/index.html.erb
app/views/cards/new.html.erb
app/views/cards/show.html.erb
app/views/containers/_container.html.erb
app/views/containers/show.html.erb
config/routes.rb

card model 串接 container model
https://user-images.githubusercontent.com/130148376/234826636-bf9a7db4-6ef0-4068-aab4-96a7f661434a.mov
#48

card model 串接 container model

---

Gemfile
Gemfile.lock
app/controllers/application_controller.rb
app/controllers/members_controller.rb
app/models/user.rb
app/views/containers/show.html.erb
app/views/layouts/application.html.erb
app/views/members/_search.html.erb
app/views/members/index.html.erb
app/views/members/new.html.erb
app/views/shared/_insidebar.html.erb
config/routes.rb
db/schema.rb

search user and add user into board

---

app/assets/stylesheets/application.tailwind.css
app/channels/application_cable/connection.rb
app/channels/room_channel.rb
app/controllers/boards_controller.rb
app/controllers/messages_controller.rb
app/controllers/rooms_controller.rb
app/helpers/messages_helper.rb
app/helpers/rooms_helper.rb
app/javascript/channels/room_channel.js
app/javascript/controllers/chatsubmit_controller.js
app/javascript/controllers/index.js
app/models/board.rb
app/models/room.rb
app/views/layouts/application.html.erb
app/views/messages/_form.html.erb
app/views/messages/_message.html.erb
app/views/messages/_mine.html.erb
app/views/messages/_theirs.html.erb
app/views/messages/create.js.erb
app/views/rooms/index.html.erb
app/views/shared/_insidebar.html.erb
config/routes.rb
config/tailwind.config.js
db/migrate/20230428060758_add_board_id_in_room.rb
db/schema.rb
test/controllers/messages_controller_test.rb
test/controllers/rooms_controller_test.rb
test/models/message_test.rb
test/models/room_test.rb

https://user-images.githubusercontent.com/87931968/235579091-0945a459-1bcd-406e-a76d-74872fe3a5bc.mp4

Issue63 room跟board做關聯,room style 調整, new message 往上推跟 alert新訊息通知

---

app/views/calendars/index.html.erb
app/views/homepages/index.html.erb
app/views/kaminari/_page.html.erb
app/views/shared/_insidebar.html.erb
app/views/shared/_navbar.html.erb

主頁增加登出，分頁增加一點樣式
首頁增加登出、前往看板
日曆增加捲軸 跟寬度調整

主頁增加登出按鈕/修改樣式

---

app/controllers/cards_controller.rb
app/helpers/application_helper.rb
app/javascript/channels/room_channel.js
app/javascript/controllers/chatsubmit_controller.js
app/jobs/send_message_job.rb
app/models/card.rb
app/models/message.rb
app/views/messages/_message.html.erb
app/views/messages/_mine.html.erb
app/views/messages/_theirs.html.erb
config/tailwind.config.js
db/migrate/20230504022737_add_card_id_in_message.rb
db/schema.rb

在新增卡片傳送一個新增卡片得訊息
https://user-images.githubusercontent.com/87931968/236193078-c9ee7665-0a54-40a0-a8cc-7c2eea6a7b35.mp4

Issue79 新增卡片傳送訊息

---

app/controllers/api/v1/cards_controller.rb
app/javascript/controllers/sortable_controller.js
app/models/board.rb
app/models/card.rb
app/models/container.rb
app/views/boards/show.html.erb
app/views/containers/_container.html.erb
app/views/containers/index.html.erb
db/migrate/20230504104024_add_position_to_containers.rb
db/schema.rb

fixed card sortable

---

app/javascript/controllers/flatpickr_controller.js
app/javascript/controllers/index.js
app/javascript/utils/notify.js
app/views/cards/edit.html.erb
package.json
yarn.lock

use flatpickr

---

app/assets/stylesheets/application.tailwind.css
app/views/homepages/index.html.erb
app/views/layouts/homepage.html.erb
app/views/shared/_footer.html.erb
app/views/shared/_navbar.html.erb

homepage RWD

---

app/views/boards/index.html.erb
app/views/boards/show.html.erb
app/views/cards/edit.html.erb
app/views/cards/new.html.erb
app/views/cards/show.html.erb
app/views/containers/_container.html.erb
app/views/containers/new.html.erb
app/views/members/index.html.erb
app/views/messages/_message.html.erb
app/views/payments/index.html.erb

https://github.com/trello123/Disboard-demo-/assets/120033213/54ead5c5-b673-43bb-bcb6-d4e20ab21972
https://github.com/trello123/Disboard-demo-/assets/120033213/36ad8cb3-e1fc-4bf1-af8b-560f27d5f28d
修正RWD排版
- payment頁面線距
- board總表跑版
- 新增container看不到字
- member頁面跑版
- message container及card名字太長跑版
- card new show edit 頁面跑版

fixed all view RWD bug

---

app/javascript/controllers/calendar_controller.js
app/views/comments/edit.html.erb
app/views/comments/new.html.erb

連動任務標籤日曆顏色
評論的英文修正
https://github.com/trello123/Disboard-demo-/assets/130148376/87f8f741-de82-40ef-8a86-9e023f643399

連動任務標籤日曆顏色

---

app/assets/stylesheets/actiontext.scss
app/assets/stylesheets/application.tailwind.css
app/controllers/boards_controller.rb
app/controllers/comments_controller.rb
app/controllers/containers_controller.rb
app/javascript/controllers/hotkey_controller.js
app/javascript/controllers/intro_controller.js
app/javascript/controllers/modal_controller.js
app/views/boards/_board.html.erb
app/views/boards/index.html.erb
app/views/boards/new.html.erb
app/views/boards/show.html.erb
app/views/cards/edit.html.erb
app/views/cards/new.html.erb
app/views/cards/show.html.erb
app/views/comments/_comment.html.erb
app/views/comments/edit.html.erb
app/views/containers/_container.html.erb
app/views/devise/registrations/new.html.erb
app/views/devise/sessions/new.html.erb
app/views/homepages/index.html.erb
app/views/layouts/application.html.erb
app/views/layouts/homepage.html.erb
app/views/shared/_sidebar.html.erb
config/tailwind.config.js
db/schema.rb
public/404.html

https://github.com/trello123/Disboard-demo-/assets/87931968/3922ba4b-1030-46cc-9fce-c7eaef419ee5

Issue114 card new edit show modal

---

app/assets/stylesheets/application.tailwind.css
app/controllers/users/registrations_controller.rb
app/views/cards/edit.html.erb
app/views/cards/new.html.erb
app/views/cards/show.html.erb
app/views/comments/edit.html.erb
app/views/containers/_container.html.erb
app/views/devise/registrations/edit.html.erb
app/views/devise/registrations/new.html.erb
app/views/devise/sessions/new.html.erb
app/views/layouts/application.html.erb
app/views/shared/_insidebar.html.erb
config/routes.rb

Issue131 新增使用者個人資資訊頁面

---

app/controllers/application_controller.rb
app/controllers/boards_controller.rb
app/controllers/invitations_controller.rb
app/controllers/members_controller.rb
app/models/board_user.rb
app/policies/board_policy.rb
app/views/invitations/index.html.erb
app/views/shared/_insidebar.html.erb
config/routes.rb
db/migrate/20230521131506_add_board_users_column_role.rb
db/schema.rb

https://github.com/trello123/Disboard-demo-/assets/72022753/f3e6c435-f061-4850-9b93-3a86b12effc2
被邀請的人
可以確認邀請或取消邀請

board_users add column role and add board invite feature

---

app/controllers/boards_controller.rb
app/views/boards/_board.html.erb

https://github.com/trello123/Disboard-demo-/assets/72022753/9eb36be1-780f-4af2-855f-07b052a88df7

member leave board

---

Gemfile
Gemfile.lock
app/controllers/boards_controller.rb
app/helpers/application_helper.rb
app/views/boards/chart.html.erb
app/views/invitations/index.html.erb
app/views/members/_search.html.erb
app/views/members/index.html.erb
app/views/shared/_insidebar.html.erb
config/initializers/chartkick.rb
db/schema.rb
spec/factories/board_users.rb
spec/factories/boards.rb
spec/factories/cards.rb
spec/factories/containers.rb
spec/factories/users.rb
spec/features/board_spec.rb
spec/features/card_spec.rb
spec/features/container_spec.rb
spec/features/user_spec.rb
spec/rails_helper.rb

fixed dashboard style bug

---

app/controllers/users/registrations_controller.rb
app/models/user.rb
app/views/devise/registrations/edit.html.erb

修掉個人資訊需要密碼認證

---

public/404.html
public/500.html

https://github.com/trello123/Disboard-demo-/assets/130148376/026de6e8-2e47-4e2f-ba0b-1c53da094092

增加500畫面404回到首頁

---

app/assets/stylesheets/application.tailwind.css
app/javascript/controllers/index.js
app/javascript/controllers/newcard_controller.js
app/views/cards/new.html.erb

新增任務傳送空表單新增按鈕消失
第 2 動作後按 X， cards 頁面所有的 cards 消失
我解決這段feedback
我讓input有值button才能按
避免沒有值還可以送出表單

Add a new card and add it to verify

---

app/controllers/boards_controller.rb
app/views/boards/_board.html.erb
app/views/boards/index.html.erb

https://github.com/trello123/Disboard-demo-/assets/87931968/732ae4b1-f28e-4e29-a527-047f5c8c9456

fixed board list page style

---

app/assets/stylesheets/application.tailwind.css
app/javascript/controllers/navbar_controller.js
app/views/devise/registrations/edit.html.erb
app/views/invitations/index.html.erb
app/views/members/index.html.erb
app/views/shared/_insidebar.html.erb

fixed rwd menu

---

app/assets/stylesheets/application.tailwind.css
app/views/boards/_board.html.erb
app/views/boards/edit.html.erb
app/views/boards/index.html.erb
app/views/boards/new.html.erb
app/views/boards/show.html.erb
app/views/containers/_container.html.erb
app/views/containers/new.html.erb

https://github.com/trello123/Disboard-demo-/assets/87931968/62a958ff-d341-4cf4-8d80-06d1b033d68f
修改一下表單的樣式跟加入modal的遮罩

issue164 fixed new/edit boaed modal and new container modal

---

app/controllers/members_controller.rb
app/views/members/_search.html.erb
app/views/members/index.html.erb
app/views/members/new.html.erb

- 需要打兩個字以上才能搜尋
- 搜尋不到會顯示 `搜尋不到關鍵字，請重新搜尋`
- 暱稱會顯示在email下方
- 假如搜尋到有很多筆 只會顯示5筆 需要再更精確輸入

modified member search rule

---

app/views/devise/registrations/new.html.erb

https://github.com/trello123/Disboard-demo-/assets/72022753/76498fc8-0f4a-457e-a226-fc75a98a0786

fixed sign up RWD

---

app/models/card.rb

fixed calender cannot read cards

---

app/views/cards/show.html.erb
app/views/containers/edit.html.erb

修改新增評論、編輯狀態 按鈕顏色“
